//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDoDungPhong
    {
        public int MaPhong { get; set; }
        public int MaVatTu { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhongThue PhongThue { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
